#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-08-07 07:51:52.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("path_measurements() works", {

  expect_error(
    fhpredict:::path_measurements()
    # argument "user_id" is missing, with no default
  )

})

