#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-08-07 07:51:48.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("api_measurements_spot() works", {

  expect_error(
    fhpredict:::api_measurements_spot()
    # HTTP request failed: Client error: (404) Not Found
  )

})

